### ISSUE TITLE
Possible assignment operator error in CEWBS.VoxelMesh.prototype.updateMesh 

### ISSUE THREAD

**Issue by jbmonroe** [TriBlade9/CEWBS#1]
Lines 165-170:

``` Javascript
if(!passID) {
    if(vertexData.positions.length > 0) {
        if(this.noVoxels = true) { // Shouldn't this be an equality test, not an assignment?
            this.isVisible = this.oldVisibility;
            this.noVoxels = false;
    }
```

**Comment by jbmonroe** [comment]
Again starting at line 184:
``` Javascript
			if(vertexData.positions.length > 0) {
				if(this.transparentMesh.noVoxels = true) { /// Equality, not assignment?
					this.transparentMesh.isVisible = this.transparentMesh.oldVisibility;
					this.transparentMesh.noVoxels = false;
				}
```

**Comment by TriBlade9** [comment]
@jbmonroe 
Ugh... looking back on this code embarrasses me.

Fixed in acad715df093af990facf47abd32f58fd114e102, although it took ages. I'm not working with 3D graphics stuff ATM. Might get back into it someday.

**Comment by jbmonroe** [comment]
Hey, I've lived that feeling myself--for weeks at a time. It took me four days to find a pair of UTF-8 encoded quotes that were breaking a single-page HTML app this week and last.  Sometimes we just don't see this stuff.  It's the life we chose, right? ;)

**Comment by TriBlade9** [comment]
@jbmonroe Yeah. I'd really enjoy working on this again if I had time off from my job, but no such luck. >_>

**Comment by kevzettler** [comment]
Can this issue be closed?

**Comment by jbmonroe** [comment]
Yes!
